BATCH_SIZE = 32
COMPLEXITY_DATASET = 1
TOTAL_EXAMPLES = 20000
LEARNING_RATE = 0.0005 #era 0.0001


EPOCHS = 150
EARLY_STOPPING_DELTA = 0.5 #percentage of increase in best loss
PATIENCE = 20
MODEL_SAVING_INTERVAL = 10000
DEBUG_MODE = False
LIMIT = 150


TRAIN_WITH_A_SUBSET = False
SUBSET_SIZE = 2000
STRATIFY = True
SUBSET_SEED = 42
VALIDATION_INTERVAL = 3

BUILDING_PREDICATES = False
CONCEPT_PREDICATES = False
active_ontology = "NEW_ONTOLOGY3" #it has a default, so check rules_and_concepts.py for the different possibilites




